In [207]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import matplotlib

import warnings
warnings.filterwarnings('ignore')

In [208]:
import matplotlib.pyplot as plt
import matplotlib as mpl
plt.rcParams['font.family'] = 'NanumGothic'
mpl.rcParams['axes.unicode_minus'] = False

# 데이터 불러오기

## sale

In [209]:
sale= pd.read_csv("/home/piai/바탕화면/BigData_Project/rental_Project/dataFolder/01 rental_sales_data.csv", encoding = 'utf-8')
# sale

In [210]:
# sale[sale['고객ID'].duplicated()]

In [211]:
sale[sale.duplicated(subset=['고객ID', '계약일', '제품군'], keep=False)]

고객ID 판매유형  계약유형    유통경로         계약일  계약기간  납부유형     제품군   월랜탈비용  \
40     25742687   렌탈    일반    영업방판  25-10-2022    60   CMS   DES-2   96900   
41     25742687   렌탈    일반    영업방판  25-10-2022    60   CMS   DES-2   96900   
205    25777820   렌탈  프로모션    R유통사  25-10-2022    36  가상계좌   DES-1  180750   
206    25777820   렌탈  프로모션    R유통사  25-10-2022    36  가상계좌   DES-1  180750   
207    25777820   렌탈  프로모션    R유통사  25-10-2022    36  가상계좌   DES-1  180750   
...         ...  ...   ...     ...         ...   ...   ...     ...     ...   
51302  66579515  NaN  프로모션   R관리방판  07-02-2023    60   무통장  DES-3A   96900   
51303  66799558   렌탈    일반    영업방판  07-02-2023    60  카드이체   DES-1   96900   
51304  66799197   렌탈  프로모션  홈쇼핑/방송  07-02-2023    39   무통장     ERA  120900   
51305  66792778  NaN    일반    렌탈총판  07-02-2023    60  카드이체   DES-1   96900   
51306  66799607   렌탈    일반    하이마트  07-02-2023    60   CMS   DES-1   96900   

       계약상태  연체건수 연체여부    신용등급    결제은행 해약여부  
40     계약확정     0   없음     NaN  SC제일은행   정상  
41     계약확정     0   없음     NaN  SC제일은행   정상  
205    계약확정     1   있음     NaN     NaN   정상  
206    계약확정     1   있음     NaN     NaN   정상  
207    계약확정     1   있음     NaN     NaN   정상  
...     ...   ...  ...     ...     ...  ...  
51302  계약확정     0   없음     NaN    롯데카드   정상  
51303  해약확정     0   없음 8.00000    롯데카드   해약  
51304  해약확정     0   없음 1.00000     NaN   해약  
51305  계약확정     0   없음 2.00000    신한카드   정상  
51306  해약확정     0   없음 8.00000  농협회원조합   해약  

[1882 rows x 15 columns]

In [212]:
sale['총 렌탈대수'] = sale.groupby(['고객ID', '계약일', '제품군'])['고객ID'].transform('count')
sale

고객ID 판매유형  계약유형    유통경로         계약일  계약기간  납부유형     제품군   월랜탈비용  \
0      66758234   렌탈    일반  서비스 방문  24-10-2022    60   CMS   DES-1   96900   
1      66755948   렌탈  교체렌탈  서비스 방문  24-10-2022    60  카드이체   DES-1  102900   
2      66756657   렌탈    일반  홈쇼핑/방송  24-10-2022    60   CMS   DES-1   96900   
3      66423450  멤버십  멤버십S   렌탈재계약  24-10-2022    12   CMS   DES-1   66900   
4      66423204  멤버십  멤버십S   렌탈재계약  24-10-2022    12   CMS   DES-1   66900   
...         ...  ...   ...     ...         ...   ...   ...     ...     ...   
51302  66579515  NaN  프로모션   R관리방판  07-02-2023    60   무통장  DES-3A   96900   
51303  66799558   렌탈    일반    영업방판  07-02-2023    60  카드이체   DES-1   96900   
51304  66799197   렌탈  프로모션  홈쇼핑/방송  07-02-2023    39   무통장     ERA  120900   
51305  66792778  NaN    일반    렌탈총판  07-02-2023    60  카드이체   DES-1   96900   
51306  66799607   렌탈    일반    하이마트  07-02-2023    60   CMS   DES-1   96900   

       계약상태  연체건수 연체여부    신용등급    결제은행 해약여부  총 렌탈대수  
0      계약확정     0   없음 9.00000   새마을금고   정상 1.00000  
1      계약확정     0   없음 2.00000    현대카드   정상 1.00000  
2      계약확정     0   없음 8.00000    우리은행   정상 1.00000  
3      계약확정     0   없음 5.00000  농협회원조합   정상 1.00000  
4      해약확정    12   있음 8.00000  농협회원조합   해약 1.00000  
...     ...   ...  ...     ...     ...  ...     ...  
51302  계약확정     0   없음     NaN    롯데카드   정상 2.00000  
51303  해약확정     0   없음 8.00000    롯데카드   해약 2.00000  
51304  해약확정     0   없음 1.00000     NaN   해약 2.00000  
51305  계약확정     0   없음 2.00000    신한카드   정상 2.00000  
51306  해약확정     0   없음 8.00000  농협회원조합   해약 2.00000  

[51307 rows x 16 columns]

In [213]:
grouped_df = sale.groupby(['고객ID', '계약일', '제품군'])

# 그룹화된 데이터프레임 확인
# for name, group in grouped_df:
#     print(f"Group Name: {name}")
#     display(group)
#     print("\n")

In [214]:
sale["총 렌탈대수"].unique()

array([ 1.,  2.,  5., nan,  6.,  3.,  4.,  9.,  8., 16.,  7., 21., 11.,
       14., 10., 13., 17., 15., 12., 18.])

In [215]:
sale[sale["총 렌탈대수"].isna()]

고객ID 판매유형 계약유형    유통경로         계약일  계약기간 납부유형  제품군  월랜탈비용  계약상태  \
277  66758695   렌탈   일반  홈쇼핑/방송  25-10-2022    60  CMS  NaN  96900  계약확정   

     연체건수 연체여부    신용등급  결제은행 해약여부  총 렌탈대수  
277     0   없음 2.00000  부산은행   정상     NaN

## business

In [216]:
business= pd.read_csv("/home/piai/바탕화면/BigData_Project/rental_Project/dataFolder/02 rental_member_data_business.csv", encoding = 'utf-8')
# business

In [217]:
business[business.duplicated()]

Empty DataFrame
Columns: [고객ID, 고객유형, 생년, 생월, 거주지, 시, 구군, 남여구분]
Index: []

In [218]:
business[business["고객ID"] == 25777820]

고객ID  고객유형  생년  생월  거주지    시     구군 남여구분
17  25777820   사업자 NaN NaN  경기도  경기도   남양주시   여자

In [219]:
business[~business['고객ID'].astype(str).str.startswith('2')]["고객ID"].values

array([66758487, 66760104, 66251159, 66764979, 66167264, 66777811,
       66785171, 66721723, 66795951, 66798213])

## personal

In [220]:
personal= pd.read_csv("/home/piai/바탕화면/BigData_Project/rental_Project/dataFolder/03 rental_member_data_personal.csv", encoding = 'utf-8')
personal

고객ID 고객유형         생년       생월    거주지      시        구군 남여구분
0      66758234   개인 1979.00000 12.00000    경기도    경기도       평택시   여자
1      66755948   개인 1982.00000  7.00000    경기도    경기도       평택시   남자
2      66756657   개인 1973.00000  4.00000    경기도    경기도       평택시   여자
3      66423450   개인 1982.00000 11.00000    경기도    경기도       포천시   남자
4      66423204   개인 1961.00000 11.00000    경기도    경기도       포천시   남자
...         ...  ...        ...      ...    ...    ...       ...  ...
40041  66579515   개인 1974.00000  7.00000    경기도    경기도   성남시 중원구   남자
40042  66799558   개인 1979.00000 10.00000    경기도    경기도   성남시 중원구   여자
40043  66799197   개인 1956.00000  4.00000  서울특별시  서울특별시       성동구   여자
40044  66792778   개인 1967.00000 10.00000  서울특별시  서울특별시       성동구   여자
40045  66799607   개인 1968.00000  3.00000  서울특별시  서울특별시       성동구   여자

[40046 rows x 8 columns]

In [221]:
personal.describe()

고객ID            생년          생월
count    40046.00000   36245.00000 36245.00000
mean  66662088.19910    2031.43112     6.27951
std     351680.80090   10546.16926     3.56530
min   25741496.00000     195.00000     1.00000
25%   66597707.75000    1964.00000     3.00000
50%   66768575.00000    1972.00000     6.00000
75%   66783600.75000    1979.00000     9.00000
max   66969860.00000 1999978.00000    12.00000

In [222]:
personal[~personal['고객ID'].astype(str).str.startswith('6')]

고객ID 고객유형         생년      생월    거주지      시    구군 남여구분
7962   25741496   개인 1965.00000 1.00000  서울특별시  서울특별시   성북구   남자
26892  25749146   개인 1983.00000 1.00000    전라도  광주광역시    동구   남자

# 합치기

In [223]:
business['고객ID'].isin(sale['고객ID']).sum()

3590

In [224]:
personal['고객ID'].isin(sale['고객ID']).sum()

40046

In [225]:
bp = pd.concat([business, personal], axis = 0)
bp

고객ID  고객유형         생년       생월    거주지      시        구군 남여구분
0      25702131   사업자        NaN      NaN    경기도    경기도       화성시   여자
1      25742841   사업자 1964.00000  8.00000    경기도    경기도       가평군   여자
2      25742683   사업자 1973.00000 12.00000  서울특별시  서울특별시       강남구   여자
3      25851817   사업자        NaN      NaN  서울특별시  서울특별시       강남구   여자
4      25742687   사업자 1958.00000  6.00000  서울특별시  서울특별시       강남구   여자
...         ...   ...        ...      ...    ...    ...       ...  ...
40041  66579515    개인 1974.00000  7.00000    경기도    경기도   성남시 중원구   남자
40042  66799558    개인 1979.00000 10.00000    경기도    경기도   성남시 중원구   여자
40043  66799197    개인 1956.00000  4.00000  서울특별시  서울특별시       성동구   여자
40044  66792778    개인 1967.00000 10.00000  서울특별시  서울특별시       성동구   여자
40045  66799607    개인 1968.00000  3.00000  서울특별시  서울특별시       성동구   여자

[43636 rows x 8 columns]

In [226]:
df = pd.merge(sale, bp, on='고객ID', how='left')
# df

In [227]:
# 열의 순서 변경하기
cols = df.columns.tolist()
cols.remove('해약여부')  # '해약여부' 열을 리스트에서 제거
cols.append('해약여부')  # '해약여부' 열을 리스트의 마지막에 추가
df = df[cols]

In [228]:
df.columns

Index(['고객ID', '판매유형', '계약유형', '유통경로', '계약일', '계약기간', '납부유형', '제품군', '월랜탈비용',
       '계약상태', '연체건수', '연체여부', '신용등급', '결제은행', '총 렌탈대수', '고객유형', '생년', '생월',
       '거주지', '시', '구군', '남여구분', '해약여부'],
      dtype='object')

In [229]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 51307 entries, 0 to 51306
Data columns (total 23 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   고객ID    51307 non-null  int64  
 1   판매유형    51303 non-null  object 
 2   계약유형    51306 non-null  object 
 3   유통경로    51307 non-null  object 
 4   계약일     51307 non-null  object 
 5   계약기간    51307 non-null  int64  
 6   납부유형    51307 non-null  object 
 7   제품군     51306 non-null  object 
 8   월랜탈비용   51307 non-null  int64  
 9   계약상태    51307 non-null  object 
 10  연체건수    51307 non-null  int64  
 11  연체여부    51305 non-null  object 
 12  신용등급    42524 non-null  float64
 13  결제은행    48547 non-null  object 
 14  총 렌탈대수  51306 non-null  float64
 15  고객유형    51305 non-null  object 
 16  생년      44336 non-null  float64
 17  생월      44336 non-null  float64
 18  거주지     51304 non-null  object 
 19  시       51304 non-null  object 
 20  구군      51305 non-null  object 
 21  남여구분    51305 non-null  object 
 22

In [230]:
df.describe()

고객ID         계약기간           월랜탈비용        연체건수        신용등급  \
count    51307.00000  51307.00000     51307.00000 51307.00000 42524.00000   
mean  62664794.78233     67.34245    113483.63292     0.16103     3.42893   
std   12160833.09732   2648.66663   4414418.21878     1.12232     2.21361   
min   25687984.00000     12.00000     54603.00000    -1.00000     0.00000   
25%   66431489.50000     60.00000     81900.00000     0.00000     1.00000   
50%   66765783.00000     60.00000     96900.00000     0.00000     3.00000   
75%   66781606.50000     60.00000     98400.00000     0.00000     5.00000   
max   66969860.00000 600000.00000 999999999.00000    15.00000    10.00000   

           총 렌탈대수            생년          생월  
count 51306.00000   44336.00000 44336.00000  
mean      1.13488    2020.42667     6.27341  
std       1.08541    9535.44096     3.56201  
min       1.00000     195.00000     1.00000  
25%       1.00000    1964.00000     3.00000  
50%       1.00000    1972.00000     6.00000  
75%       1.00000    1979.00000     9.00000  
max      21.00000 1999978.00000    12.00000

In [231]:
df.isnull().sum()

고객ID         0
판매유형         4
계약유형         1
유통경로         0
계약일          0
계약기간         0
납부유형         0
제품군          1
월랜탈비용        0
계약상태         0
연체건수         0
연체여부         2
신용등급      8783
결제은행      2760
총 렌탈대수       1
고객유형         2
생년        6971
생월        6971
거주지          3
시            3
구군           2
남여구분         2
해약여부        25
dtype: int64

# 전처리

## 결측치

In [232]:
# 해약여부 결측치 삭제
df.dropna(subset = ["해약여부"], inplace = True)
# df

In [233]:
df.loc[df["계약유형"] == "교체렌탈", "판매유형"] = "렌탈"

In [234]:
# 판매유형 결측치 삭제
df.dropna(subset = ["판매유형"], inplace = True)

In [235]:
# 계약유형 결측치 삭제
df.dropna(subset = ["계약유형"], inplace = True)

In [236]:
# 제품군 결측치 삭제
df.dropna(subset = ["제품군"], inplace = True)

In [237]:
df[df["연체여부"].isna()][["연체건수","연체여부"]]

연체건수 연체여부
182     2  NaN
255     0  NaN

In [238]:
df["연체여부"].unique()

array(['없음', '있음', nan], dtype=object)

In [239]:
# 연체건수 따른 연체여부 설정
df.loc[(df["연체여부"].isna()) & (df["연체건수"] == 0), "연체여부"] = "없음"
df.loc[(df["연체여부"].isna()) & (df["연체건수"] >= 1), "연체여부"] = "있음"
df["연체여부"].unique()

array(['없음', '있음'], dtype=object)

In [240]:
df[df["거주지"].isna()]

고객ID 판매유형 계약유형  유통경로         계약일  계약기간 납부유형    제품군   월랜탈비용  계약상태  \
298  66758696   렌탈   일반  렌탈총판  25-10-2022    60  CMS  DES-1  105900  계약확정   

     ...  결제은행  총 렌탈대수  고객유형         생년      생월  거주지      시   구군 남여구분 해약여부  
298  ...  국민은행 1.00000    개인 1988.00000 5.00000  NaN  광주광역시   북구   여자   정상  

[1 rows x 23 columns]

In [241]:
df["거주지"].unique()

array(['경기도', '경상도', '전라도', '충청도', '강원도', '서울특별시', nan, '제주도', '광주광역시'],
      dtype=object)

In [242]:
df["거주지"].fillna("광주광역시", inplace=True)

In [243]:
df[df["시"].isna()]

고객ID 판매유형 계약유형    유통경로         계약일  계약기간 납부유형    제품군  월랜탈비용  계약상태  \
109  25742697   렌탈   일반  서비스 방문  25-10-2022    60  CMS  DES-1  96900  계약확정   

     ...  결제은행  총 렌탈대수  고객유형         생년      생월  거주지    시    구군 남여구분 해약여부  
109  ...  국민은행 1.00000   사업자 1979.00000 5.00000  경기도  NaN   광주시   여자   정상  

[1 rows x 23 columns]

In [244]:
df["시"].unique()

array(['경기도', '경상도', '전라도', '부산광역시', '충청도', '강원도', '서울특별시', '인천광역시',
       '광주광역시', nan, '울산광역시', '대구광역시', '대전광역시', '제주도', '세종자치시'],
      dtype=object)

In [245]:
df["시"].fillna("경기도", inplace=True)

In [246]:
df["생년"].fillna("unknown", inplace=True)

In [247]:
df.drop("생월", axis = 1, inplace = True)
# df

In [248]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 51277 entries, 0 to 51306
Data columns (total 22 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   고객ID    51277 non-null  int64  
 1   판매유형    51277 non-null  object 
 2   계약유형    51277 non-null  object 
 3   유통경로    51277 non-null  object 
 4   계약일     51277 non-null  object 
 5   계약기간    51277 non-null  int64  
 6   납부유형    51277 non-null  object 
 7   제품군     51277 non-null  object 
 8   월랜탈비용   51277 non-null  int64  
 9   계약상태    51277 non-null  object 
 10  연체건수    51277 non-null  int64  
 11  연체여부    51277 non-null  object 
 12  신용등급    42498 non-null  float64
 13  결제은행    48517 non-null  object 
 14  총 렌탈대수  51277 non-null  float64
 15  고객유형    51277 non-null  object 
 16  생년      51277 non-null  object 
 17  거주지     51277 non-null  object 
 18  시       51277 non-null  object 
 19  구군      51277 non-null  object 
 20  남여구분    51277 non-null  object 
 21  해약여부    51277 non-null  object 
dty

## 이상치

### 월랜탈비용

In [249]:
df["월랜탈비용"].unique()

array([    96900,    102900,     66900,     90900,     98400,     80400,
          105900,     81900, 999999999,    111900,     87900,    134700,
           89400,    142200,     96600,    126900,    124200,     75900,
          125700,     78900,    104400,    115200,    110700,    145200,
          180750,    185700,     55200,    120900,    108900,    118200,
           84900,    123000,     72900,    127200,    144900,    121200,
          112200,    109200,    133200,    141900,    116700,    114150,
          138900,    151200,    111300,    215700,    134400,    137700,
           99900,    101550,    136950,     93900,    129900,     95400,
          113700,    101400,    167700,    117900,     98910,    107700,
          100200,    130200,    102450,    136200,    119400,    110400,
          104700,     85350,     99600,     54603,     56979,     58743,
           60225,     66396,     72138,     77154,     77985,     62673,
           64326,     87960,     87930,    155700, 

In [250]:
# df[df["월랜탈비용"] == 999999999]

In [251]:
df["고객유형"].unique()

array([' 개인', ' 사업자'], dtype=object)

In [252]:
df["고객유형"].replace({' 개인':"개인", ' 사업자':"사업자"}, inplace = True)
df["고객유형"].unique()

array(['개인', '사업자'], dtype=object)

In [253]:
# 판매유형, 계약유형, 제품군, 계약기간, 납부유형, 고객유형 비교
selected_rows = df[(df["판매유형"] == "렌탈") & (df["계약유형"] == "프로모션") & (df["제품군"] == "DES-1") & (df["납부유형"] == "CMS") & (df["월랜탈비용"] != 999999999) & (df["연체여부"] == "없음")]
# selected_rows

In [254]:
selected_rows["월랜탈비용"].describe()

count     6970.00000
mean    105258.33572
std       9563.48763
min      87900.00000
25%      96900.00000
50%     105900.00000
75%     105900.00000
max     167700.00000
Name: 월랜탈비용, dtype: float64

In [255]:
df["월랜탈비용"].replace(999999999, 105900, inplace=True)
df["월랜탈비용"].unique()

array([ 96900, 102900,  66900,  90900,  98400,  80400, 105900,  81900,
       111900,  87900, 134700,  89400, 142200,  96600, 126900, 124200,
        75900, 125700,  78900, 104400, 115200, 110700, 145200, 180750,
       185700,  55200, 120900, 108900, 118200,  84900, 123000,  72900,
       127200, 144900, 121200, 112200, 109200, 133200, 141900, 116700,
       114150, 138900, 151200, 111300, 215700, 134400, 137700,  99900,
       101550, 136950,  93900, 129900,  95400, 113700, 101400, 167700,
       117900,  98910, 107700, 100200, 130200, 102450, 136200, 119400,
       110400, 104700,  85350,  99600,  54603,  56979,  58743,  60225,
        66396,  72138,  77154,  77985,  62673,  64326,  87960,  87930,
       155700, 113460, 131400,  68625, 113400, 126450, 105300,  90930,
       131700,  60603, 114900,  89100,  82200,  80310])

### 연체건수

In [256]:
df["연체건수"].unique()

array([ 0, 12,  1, 15,  4,  2,  9, 10,  7,  5, 11, 13,  3, -1,  8, 14,  6])

In [257]:
# df[df["연체건수"] == -1][["연체건수", "연체여부"]]

In [258]:
# df["연체건수"].replace(-1, 0, inplace=True)
# df["연체건수"].unique()

### 계약기간

In [259]:
# df["계약기간"].unique()

In [260]:
# df[(df["계약기간"] == 600) | (df["계약기간"] == 600000)]

In [261]:
df["계약기간"].replace({600: 60, 600000: 60}, inplace=True)
df["계약기간"].unique()

array([60, 12, 36, 39])

### 생년

In [262]:
sorted(df[df["생년"] != "unknown"]["생년"].unique())

[195.0,
 197.0,
 1919.0,
 1922.0,
 1925.0,
 1926.0,
 1927.0,
 1928.0,
 1929.0,
 1930.0,
 1931.0,
 1932.0,
 1933.0,
 1934.0,
 1935.0,
 1936.0,
 1937.0,
 1938.0,
 1939.0,
 1940.0,
 1941.0,
 1942.0,
 1943.0,
 1944.0,
 1945.0,
 1946.0,
 1947.0,
 1948.0,
 1949.0,
 1950.0,
 1951.0,
 1952.0,
 1953.0,
 1954.0,
 1955.0,
 1956.0,
 1957.0,
 1958.0,
 1959.0,
 1960.0,
 1961.0,
 1962.0,
 1963.0,
 1964.0,
 1965.0,
 1966.0,
 1967.0,
 1968.0,
 1969.0,
 1970.0,
 1971.0,
 1972.0,
 1973.0,
 1974.0,
 1975.0,
 1976.0,
 1977.0,
 1978.0,
 1979.0,
 1980.0,
 1981.0,
 1982.0,
 1983.0,
 1984.0,
 1985.0,
 1986.0,
 1987.0,
 1988.0,
 1989.0,
 1990.0,
 1991.0,
 1992.0,
 1993.0,
 1994.0,
 1995.0,
 1996.0,
 199982.0,
 1999978.0]

In [263]:
df["생년"].replace({199982: 1982, 1999978: 1978}, inplace=True)
# df["생년"].unique()

In [264]:
df.drop(df[(df["생년"] == 195) | (df["생년"] == 197)].index, inplace = True)
# df["생년"].unique()

# 최종

In [265]:
# df

# 총 렌탈대수 파생변수

In [266]:
df['총렌탈대수'] = df.groupby(['고객ID', '계약일', '제품군'])['고객ID'].transform('count')
# df

In [267]:
# '계약상태'가 '기간만료', '해약확정', '해약진행중'인 경우 '이탈'로, 그 외는 '정상'으로 분류하는 새로운 컬럼 '이탈여부' 생성
df['이탈여부'] = df['계약상태'].apply(lambda x: '이탈' if x in ['기간만료', '해약확정', '해약진행중'] else '정상')
# 결과 확인을 위해 상위 몇 개의 데이터를 출력
print(df[['고객ID', '계약상태', '이탈여부']].head())

       고객ID  계약상태 이탈여부
0  66758234  계약확정   정상
1  66755948  계약확정   정상
2  66756657  계약확정   정상
3  66423450  계약확정   정상
4  66423204  해약확정   이탈


In [268]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 51275 entries, 0 to 51306
Data columns (total 24 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   고객ID    51275 non-null  int64  
 1   판매유형    51275 non-null  object 
 2   계약유형    51275 non-null  object 
 3   유통경로    51275 non-null  object 
 4   계약일     51275 non-null  object 
 5   계약기간    51275 non-null  int64  
 6   납부유형    51275 non-null  object 
 7   제품군     51275 non-null  object 
 8   월랜탈비용   51275 non-null  int64  
 9   계약상태    51275 non-null  object 
 10  연체건수    51275 non-null  int64  
 11  연체여부    51275 non-null  object 
 12  신용등급    42497 non-null  float64
 13  결제은행    48515 non-null  object 
 14  총 렌탈대수  51275 non-null  float64
 15  고객유형    51275 non-null  object 
 16  생년      51275 non-null  object 
 17  거주지     51275 non-null  object 
 18  시       51275 non-null  object 
 19  구군      51275 non-null  object 
 20  남여구분    51275 non-null  object 
 21  해약여부    51275 non-null  object 
 22

In [269]:
df["구군"] = df["구군"].apply(lambda x: x.strip())
df.loc[(df['구군'] == '여주군'), '구군'] = '여주시'
df['구군'] = df['구군'].replace({'청원군': '청주시'})

In [270]:
df['계약일'] = pd.to_datetime(df['계약일'], format='%d-%m-%Y')
# Extract the weekday from '계약일'
df['요일'] = df['계약일'].dt.dayofweek
# Map the weekday numbers to day names (optional)
day_names = {0: '월요일', 1: '화요일', 2: '수요일', 3: '목요일', 4: '금요일', 5: '토요일', 6: '일요일'}
df['요일'] = df['요일'].map(day_names)
# Now, '요일' contains the day of the week for each contract date

# '계약상태'가 '기간만료', '해약확정', '해약진행중'인 경우 '이탈'로, 그 외는 '정상'으로 분류하는 새로운 컬럼 '이탈여부' 생성
df['이탈여부'] = df['계약상태'].apply(lambda x: '이탈' if x in ['기간만료', '해약확정', '해약진행중'] else '정상')
# 결과 확인을 위해 상위 몇 개의 데이터를 출력
# print(df[['고객ID', '계약상태', '이탈여부']].head())

In [271]:
current_year = 2024
def calculate_age(birth_year):
    if birth_year != 'unknown':
        return current_year - float(birth_year)
    else:
        return None
df['나이'] = df['생년'].apply(calculate_age)

In [272]:
def calculate_age_group(age):
    if age is not None:
        if age < 20:
            return '10대 미만'
        elif age < 30:
            return '20대'
        elif age < 40:
            return '30대'
        elif age < 50:
            return '40대'
        elif age < 60:
            return '50대'
        elif age < 70:
            return '60대'
        elif age < 80:
            return '70대'
        else:
            return '80대 이상'
    else:
        return None
# 연령대를 계산하여 새로운 열에 추가
df['연령대'] = df['나이'].apply(calculate_age_group)

In [273]:
e_mart = ['부산광역시 사상구', '서울특별시 성동구', '서울특별시 구로구', '경기도 남양주시',
               '경기도 수원시권선구', '인천시 연수구', '부산광역시 연제구', '서울특별시 영등포구', '경기도 고양시일산서구'] # 수원시, 고양시
hi_mart = ['서울특별시 송파구']

store = ['서울특별시 강남구', "서울특별시 노원구", "서울특별시 용산구", "경기 수원시영통구", "경기 용인시기흥구", #용인시
         "서울특별시 구로구", "대구 수성구", "부산 해운대구", "광주 서구", "인천 남동구"]

def check_location_mart(location):
    for location_list in [e_mart, hi_mart]:
        for item in location_list:
            if item.split(' ')[-1] in location:
                return 1
    return 0

def check_location_store(location):
    for location_list in [store]:
        for item in location_list:
            if item.split(' ')[-1] in location:
                return 1
    return 0

df['마트'] = df['구군'].apply(check_location_mart)

df['직영점'] = df['구군'].apply(check_location_store)

In [274]:
pd.set_option('display.max_seq_items', None)
# df = pd.read_csv("/home/piai/바탕화면/BigData_Project/rental_Project/dataFolder/rental.csv")
incomes = pd.read_csv("/home/piai/바탕화면/BigData_Project/rental_Project/dataFolder/incomes.csv", encoding='euc-kr', skiprows=2)
# incomes.head()
pd.options.display.float_format = '{:.5f}'.format
incomes['지역별 소득량(평균)'] = (incomes['금액 (백만원)'] * 1000000) / incomes['인원 (명)']
incomes["행정구역(시군구)별(1)"] = incomes["행정구역(시군구)별(1)"].str.replace("서울", "서울특별시")
incomes["행정구역(시군구)별(1)"] = incomes["행정구역(시군구)별(1)"].str.replace("경기", "경기도")
incomes["행정구역(시군구)별(1)"] = incomes["행정구역(시군구)별(1)"].str.replace("경북", "경상도")
incomes["행정구역(시군구)별(1)"] = incomes["행정구역(시군구)별(1)"].str.replace("전남", "전라도")
incomes["행정구역(시군구)별(1)"] = incomes["행정구역(시군구)별(1)"].str.replace("경남", "경상도")
incomes["행정구역(시군구)별(1)"] = incomes["행정구역(시군구)별(1)"].str.replace("강원", "강원도")
incomes["행정구역(시군구)별(1)"] = incomes["행정구역(시군구)별(1)"].str.replace("부산", "부산광역시")
incomes["행정구역(시군구)별(1)"] = incomes["행정구역(시군구)별(1)"].str.replace("충남", "충청도")
incomes["행정구역(시군구)별(1)"] = incomes["행정구역(시군구)별(1)"].str.replace("전북", "전라도")
incomes["행정구역(시군구)별(1)"] = incomes["행정구역(시군구)별(1)"].str.replace("충북", "충청도")
incomes["행정구역(시군구)별(1)"] = incomes["행정구역(시군구)별(1)"].str.replace("인천", "인천광역시")
incomes["행정구역(시군구)별(1)"] = incomes["행정구역(시군구)별(1)"].str.replace("대구", "대구광역시")
incomes["행정구역(시군구)별(1)"] = incomes["행정구역(시군구)별(1)"].str.replace("광주", "광주광역시")
incomes["행정구역(시군구)별(1)"] = incomes["행정구역(시군구)별(1)"].str.replace("대전", "대전광역시")
incomes["행정구역(시군구)별(1)"] = incomes["행정구역(시군구)별(1)"].str.replace("울산", "울산광역시")
incomes["행정구역(시군구)별(1)"] = incomes["행정구역(시군구)별(1)"].str.replace("제주", "제주도")
incomes["행정구역(시군구)별(1)"] = incomes["행정구역(시군구)별(1)"].str.replace("세종", "세종자치시")
incomes.rename(columns={"행정구역(시군구)별(1)" : "시",
                        "행정구역(시군구)별(2)":"구군"}, inplace=True)
# df["구군"] = df["구군"].str.replace(" ", "")
# df["시"] = df["시"].str.replace(" ", "")
incomes['구군'] = incomes['구군'].replace({'미추홀구(남구)': '남구'})
incomes['구군'] = incomes['구군'].replace({'당진시': '당진군'})
# incomes['구군'] = incomes['구군'].replace({'여주시': '여주'})
# df['구군'] = df['구군'].replace({'여주시': '여주'})
df['구군'] = df['구군'].replace({'청원군': '청주시'})
incomes.head()
# incomes[incomes["구군"].str.contains("소계")]
# 데이터 전처리
# df["구군"] = df["구군"].apply(lambda x: x.strip())
df['구군'] = df['구군'].apply(lambda x: x.split()[0])
# df.loc[(df['구군'] == '여주군'), '구군'] = '여주시'
# df['구군'] = df['구군'].replace({'청원군': '청주시'})
incomes['구군'] = incomes['구군'].apply(lambda x: x.split()[0])
incomes.loc[(incomes['시'] == '세종자치시') & (incomes['구군'] == '소계'), '구군'] = '세종자치시'
# df.loc[0, "구군"]
df = pd.merge(left=df, right=incomes, how='left', \
                  on=['시','구군'], sort=False)
df = df.drop(['인원 (명)', '금액 (백만원)', '인원 (명).1', '금액 (백만원).1', '인원 (명).2', '금액 (백만원).2', '인원 (명).3', '금액 (백만원).3'], axis=1)
df_origin = pd.read_csv("dataFolder/rental.csv")
df['구군'] = df_origin['구군']
df.to_csv("rental.csv", index = False)

In [275]:
df.to_csv("rental_pre.csv", index=False)